version: '2'

services:
  web:
    image: ohiotoo/mage19:latest
    #build: .
    volumes:
      - /mnt/nfs:/mnt/nfs
      - /home/ec2-user/docker/nnaws/:/var/www/html/
      - ./ssl:/etc/apache2/external/
    ports:
      - 80:80
      - 443:443
